// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// AktivasiRepository is an autogenerated mock type for the AktivasiRepository type
type AktivasiRepository struct {
	mock.Mock
}

// AddSusulan provides a mock function with given fields: p
func (_m *AktivasiRepository) AddSusulan(p *entity.PesertaSusulan) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for AddSusulan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PesertaSusulan) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCourse provides a mock function with given fields: ac
func (_m *AktivasiRepository) CreateCourse(ac *entity.AktivasiCourse) error {
	ret := _m.Called(ac)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AktivasiCourse) error); ok {
		r0 = rf(ac)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSesi provides a mock function with given fields: a
func (_m *AktivasiRepository) CreateSesi(a *entity.AktivasiSesi) error {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for CreateSesi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AktivasiSesi) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSesi provides a mock function with given fields: id
func (_m *AktivasiRepository) DeleteSesi(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSesi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *AktivasiRepository) FindCourse(aktivasiSesiID int, courseID int) (*entity.AktivasiCourse, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindCourse")
	}

	var r0 *entity.AktivasiCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*entity.AktivasiCourse, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *entity.AktivasiCourse); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AktivasiCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCourseByID provides a mock function with given fields: id
func (_m *AktivasiRepository) FindCourseByID(id int) (*entity.AktivasiCourse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindCourseByID")
	}

	var r0 *entity.AktivasiCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.AktivasiCourse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.AktivasiCourse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AktivasiCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSesiByComposite provides a mock function with given fields: sesiID, kelasID, shift
func (_m *AktivasiRepository) FindSesiByComposite(sesiID int, kelasID int, shift int) (*entity.AktivasiSesi, error) {
	ret := _m.Called(sesiID, kelasID, shift)

	if len(ret) == 0 {
		panic("no return value specified for FindSesiByComposite")
	}

	var r0 *entity.AktivasiSesi
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (*entity.AktivasiSesi, error)); ok {
		return rf(sesiID, kelasID, shift)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) *entity.AktivasiSesi); ok {
		r0 = rf(sesiID, kelasID, shift)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AktivasiSesi)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(sesiID, kelasID, shift)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSesiByID provides a mock function with given fields: id
func (_m *AktivasiRepository) FindSesiByID(id int) (*entity.AktivasiSesi, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindSesiByID")
	}

	var r0 *entity.AktivasiSesi
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.AktivasiSesi, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.AktivasiSesi); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AktivasiSesi)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSusulan provides a mock function with given fields: aktivasiSesiID, mahasiswaID
func (_m *AktivasiRepository) IsSusulan(aktivasiSesiID int, mahasiswaID int) (bool, error) {
	ret := _m.Called(aktivasiSesiID, mahasiswaID)

	if len(ret) == 0 {
		panic("no return value specified for IsSusulan")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (bool, error)); ok {
		return rf(aktivasiSesiID, mahasiswaID)
	}
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(aktivasiSesiID, mahasiswaID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, mahasiswaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActiveSesi provides a mock function with no fields
func (_m *AktivasiRepository) ListActiveSesi() ([]entity.AktivasiSesi, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListActiveSesi")
	}

	var r0 []entity.AktivasiSesi
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.AktivasiSesi, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.AktivasiSesi); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AktivasiSesi)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCoursesByAktivasi provides a mock function with given fields: aktivasiSesiID
func (_m *AktivasiRepository) ListCoursesByAktivasi(aktivasiSesiID int) ([]entity.AktivasiCourse, error) {
	ret := _m.Called(aktivasiSesiID)

	if len(ret) == 0 {
		panic("no return value specified for ListCoursesByAktivasi")
	}

	var r0 []entity.AktivasiCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.AktivasiCourse, error)); ok {
		return rf(aktivasiSesiID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.AktivasiCourse); ok {
		r0 = rf(aktivasiSesiID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AktivasiCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(aktivasiSesiID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSesi provides a mock function with no fields
func (_m *AktivasiRepository) ListSesi() ([]entity.AktivasiSesi, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSesi")
	}

	var r0 []entity.AktivasiSesi
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.AktivasiSesi, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.AktivasiSesi); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AktivasiSesi)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSusulan provides a mock function with given fields: aktivasiSesiID
func (_m *AktivasiRepository) ListSusulan(aktivasiSesiID int) ([]entity.PesertaSusulan, error) {
	ret := _m.Called(aktivasiSesiID)

	if len(ret) == 0 {
		panic("no return value specified for ListSusulan")
	}

	var r0 []entity.PesertaSusulan
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.PesertaSusulan, error)); ok {
		return rf(aktivasiSesiID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.PesertaSusulan); ok {
		r0 = rf(aktivasiSesiID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PesertaSusulan)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(aktivasiSesiID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSusulanByMahasiswa provides a mock function with given fields: mahasiswaID
func (_m *AktivasiRepository) ListSusulanByMahasiswa(mahasiswaID int) ([]entity.PesertaSusulan, error) {
	ret := _m.Called(mahasiswaID)

	if len(ret) == 0 {
		panic("no return value specified for ListSusulanByMahasiswa")
	}

	var r0 []entity.PesertaSusulan
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.PesertaSusulan, error)); ok {
		return rf(mahasiswaID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.PesertaSusulan); ok {
		r0 = rf(mahasiswaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PesertaSusulan)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(mahasiswaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSusulan provides a mock function with given fields: aktivasiSesiID, mahasiswaID
func (_m *AktivasiRepository) RemoveSusulan(aktivasiSesiID int, mahasiswaID int) error {
	ret := _m.Called(aktivasiSesiID, mahasiswaID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSusulan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(aktivasiSesiID, mahasiswaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCourse provides a mock function with given fields: ac
func (_m *AktivasiRepository) UpdateCourse(ac *entity.AktivasiCourse) error {
	ret := _m.Called(ac)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AktivasiCourse) error); ok {
		r0 = rf(ac)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSesi provides a mock function with given fields: a
func (_m *AktivasiRepository) UpdateSesi(a *entity.AktivasiSesi) error {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSesi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AktivasiSesi) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAktivasiRepository creates a new instance of AktivasiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAktivasiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AktivasiRepository {
	mock := &AktivasiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
