// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// AmpuanRepository is an autogenerated mock type for the AmpuanRepository type
type AmpuanRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: a
func (_m *AmpuanRepository) Create(a *entity.AmpuanKelompok) error {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AmpuanKelompok) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *AmpuanRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with no fields
func (_m *AmpuanRepository) List() ([]entity.AmpuanKelompok, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.AmpuanKelompok
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.AmpuanKelompok, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.AmpuanKelompok); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AmpuanKelompok)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByKelas provides a mock function with given fields: kelasID
func (_m *AmpuanRepository) ListByKelas(kelasID int) ([]entity.AmpuanKelompok, error) {
	ret := _m.Called(kelasID)

	if len(ret) == 0 {
		panic("no return value specified for ListByKelas")
	}

	var r0 []entity.AmpuanKelompok
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.AmpuanKelompok, error)); ok {
		return rf(kelasID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.AmpuanKelompok); ok {
		r0 = rf(kelasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AmpuanKelompok)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(kelasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAmpuanRepository creates a new instance of AmpuanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAmpuanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AmpuanRepository {
	mock := &AmpuanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
