// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: log
func (_m *AuditLogRepository) Create(log *entity.AuditLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.AuditLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: search, role, action, page, limit, hideSuperadmin
func (_m *AuditLogRepository) FindAll(search string, role string, action string, page int, limit int, hideSuperadmin bool) ([]entity.AuditLog, int64, error) {
	ret := _m.Called(search, role, action, page, limit, hideSuperadmin)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, int, int, bool) ([]entity.AuditLog, int64, error)); ok {
		return rf(search, role, action, page, limit, hideSuperadmin)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, int, int, bool) []entity.AuditLog); ok {
		r0 = rf(search, role, action, page, limit, hideSuperadmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, int, int, bool) int64); ok {
		r1 = rf(search, role, action, page, limit, hideSuperadmin)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, int, int, bool) error); ok {
		r2 = rf(search, role, action, page, limit, hideSuperadmin)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
