// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *CourseRepository) Create(c *entity.Course) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Course) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CourseRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *CourseRepository) FindByID(id int) (*entity.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Course); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySesiJenis provides a mock function with given fields: sesiID, jenis
func (_m *CourseRepository) FindBySesiJenis(sesiID int, jenis entity.JenisCourse) (*entity.Course, error) {
	ret := _m.Called(sesiID, jenis)

	if len(ret) == 0 {
		panic("no return value specified for FindBySesiJenis")
	}

	var r0 *entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int, entity.JenisCourse) (*entity.Course, error)); ok {
		return rf(sesiID, jenis)
	}
	if rf, ok := ret.Get(0).(func(int, entity.JenisCourse) *entity.Course); ok {
		r0 = rf(sesiID, jenis)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(int, entity.JenisCourse) error); ok {
		r1 = rf(sesiID, jenis)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBySesi provides a mock function with given fields: sesiID
func (_m *CourseRepository) ListBySesi(sesiID int) ([]entity.Course, error) {
	ret := _m.Called(sesiID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySesi")
	}

	var r0 []entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.Course, error)); ok {
		return rf(sesiID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.Course); ok {
		r0 = rf(sesiID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(sesiID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c
func (_m *CourseRepository) Update(c *entity.Course) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Course) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
