// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// JadwalRepository is an autogenerated mock type for the JadwalRepository type
type JadwalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: j
func (_m *JadwalRepository) Create(j *entity.Jadwal) error {
	ret := _m.Called(j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Jadwal) error); ok {
		r0 = rf(j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *JadwalRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *JadwalRepository) FindByID(id int) (*entity.Jadwal, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Jadwal
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Jadwal, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Jadwal); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Jadwal)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByKelasShift provides a mock function with given fields: kelasID, shift
func (_m *JadwalRepository) FindByKelasShift(kelasID int, shift int) (*entity.Jadwal, error) {
	ret := _m.Called(kelasID, shift)

	if len(ret) == 0 {
		panic("no return value specified for FindByKelasShift")
	}

	var r0 *entity.Jadwal
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*entity.Jadwal, error)); ok {
		return rf(kelasID, shift)
	}
	if rf, ok := ret.Get(0).(func(int, int) *entity.Jadwal); ok {
		r0 = rf(kelasID, shift)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Jadwal)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(kelasID, shift)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *JadwalRepository) List() ([]entity.Jadwal, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Jadwal
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Jadwal, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Jadwal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Jadwal)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: j
func (_m *JadwalRepository) Update(j *entity.Jadwal) error {
	ret := _m.Called(j)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Jadwal) error); ok {
		r0 = rf(j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJadwalRepository creates a new instance of JadwalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJadwalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JadwalRepository {
	mock := &JadwalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
