// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// JawabanRepository is an autogenerated mock type for the JawabanRepository type
type JawabanRepository struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: jawabanIDs
func (_m *JawabanRepository) BulkDelete(jawabanIDs []int) error {
	ret := _m.Called(jawabanIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]int) error); ok {
		r0 = rf(jawabanIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkResetNilai provides a mock function with given fields: jawabanIDs
func (_m *JawabanRepository) BulkResetNilai(jawabanIDs []int) error {
	ret := _m.Called(jawabanIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkResetNilai")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]int) error); ok {
		r0 = rf(jawabanIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: j
func (_m *JawabanRepository) Create(j *entity.JawabanMahasiswa) error {
	ret := _m.Called(j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.JawabanMahasiswa) error); ok {
		r0 = rf(j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *JawabanRepository) FindByID(id int) (*entity.JawabanMahasiswa, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.JawabanMahasiswa
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.JawabanMahasiswa, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.JawabanMahasiswa); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.JawabanMahasiswa)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMahasiswaSoal provides a mock function with given fields: mahasiswaID, soalTerpilihID
func (_m *JawabanRepository) FindByMahasiswaSoal(mahasiswaID int, soalTerpilihID int) (*entity.JawabanMahasiswa, error) {
	ret := _m.Called(mahasiswaID, soalTerpilihID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMahasiswaSoal")
	}

	var r0 *entity.JawabanMahasiswa
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*entity.JawabanMahasiswa, error)); ok {
		return rf(mahasiswaID, soalTerpilihID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *entity.JawabanMahasiswa); ok {
		r0 = rf(mahasiswaID, soalTerpilihID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.JawabanMahasiswa)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(mahasiswaID, soalTerpilihID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllJawabanFlat provides a mock function with given fields: kelasID, sesiID, search, jenis
func (_m *JawabanRepository) GetAllJawabanFlat(kelasID int, sesiID int, search string, jenis string) ([]entity.JawabanMahasiswa, error) {
	ret := _m.Called(kelasID, sesiID, search, jenis)

	if len(ret) == 0 {
		panic("no return value specified for GetAllJawabanFlat")
	}

	var r0 []entity.JawabanMahasiswa
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]entity.JawabanMahasiswa, error)); ok {
		return rf(kelasID, sesiID, search, jenis)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []entity.JawabanMahasiswa); ok {
		r0 = rf(kelasID, sesiID, search, jenis)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.JawabanMahasiswa)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(kelasID, sesiID, search, jenis)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByMahasiswaCourse provides a mock function with given fields: mahasiswaID, aktivasiSesiID, courseID
func (_m *JawabanRepository) ListByMahasiswaCourse(mahasiswaID int, aktivasiSesiID int, courseID int) ([]entity.JawabanMahasiswa, error) {
	ret := _m.Called(mahasiswaID, aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMahasiswaCourse")
	}

	var r0 []entity.JawabanMahasiswa
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]entity.JawabanMahasiswa, error)); ok {
		return rf(mahasiswaID, aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []entity.JawabanMahasiswa); ok {
		r0 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.JawabanMahasiswa)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRekap provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *JawabanRepository) ListRekap(aktivasiSesiID int, courseID int) ([]entity.JawabanMahasiswa, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListRekap")
	}

	var r0 []entity.JawabanMahasiswa
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]entity.JawabanMahasiswa, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []entity.JawabanMahasiswa); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.JawabanMahasiswa)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSubmittedForCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *JawabanRepository) MarkSubmittedForCourse(aktivasiSesiID int, courseID int) (int64, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSubmittedForCourse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int64, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) int64); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSubmittedForMahasiswaCourse provides a mock function with given fields: mahasiswaID, aktivasiSesiID, courseID
func (_m *JawabanRepository) MarkSubmittedForMahasiswaCourse(mahasiswaID int, aktivasiSesiID int, courseID int) (int64, error) {
	ret := _m.Called(mahasiswaID, aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSubmittedForMahasiswaCourse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (int64, error)); ok {
		return rf(mahasiswaID, aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) int64); ok {
		r0 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumNilai provides a mock function with given fields: mahasiswaID, aktivasiSesiID, courseID
func (_m *JawabanRepository) SumNilai(mahasiswaID int, aktivasiSesiID int, courseID int) (float64, error) {
	ret := _m.Called(mahasiswaID, aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for SumNilai")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (float64, error)); ok {
		return rf(mahasiswaID, aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) float64); ok {
		r0 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: j
func (_m *JawabanRepository) Update(j *entity.JawabanMahasiswa) error {
	ret := _m.Called(j)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.JawabanMahasiswa) error); ok {
		r0 = rf(j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJawabanRepository creates a new instance of JawabanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJawabanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JawabanRepository {
	mock := &JawabanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
