// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// KelasRepository is an autogenerated mock type for the KelasRepository type
type KelasRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: k
func (_m *KelasRepository) Create(k *entity.Kelas) error {
	ret := _m.Called(k)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Kelas) error); ok {
		r0 = rf(k)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *KelasRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *KelasRepository) FindByID(id int) (*entity.Kelas, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Kelas
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Kelas, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Kelas); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Kelas)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *KelasRepository) List() ([]entity.Kelas, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Kelas
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Kelas, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Kelas); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Kelas)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetRegisterOpen provides a mock function with given fields: id, open
func (_m *KelasRepository) SetRegisterOpen(id int, open bool) error {
	ret := _m.Called(id, open)

	if len(ret) == 0 {
		panic("no return value specified for SetRegisterOpen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, bool) error); ok {
		r0 = rf(id, open)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: k
func (_m *KelasRepository) Update(k *entity.Kelas) error {
	ret := _m.Called(k)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Kelas) error); ok {
		r0 = rf(k)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKelasRepository creates a new instance of KelasRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKelasRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KelasRepository {
	mock := &KelasRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
