// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// KonfigurasiRepository is an autogenerated mock type for the KonfigurasiRepository type
type KonfigurasiRepository struct {
	mock.Mock
}

// All provides a mock function with no fields
func (_m *KonfigurasiRepository) All() ([]entity.Konfigurasi, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []entity.Konfigurasi
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Konfigurasi, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Konfigurasi); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Konfigurasi)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: key
func (_m *KonfigurasiRepository) Get(key string) (*entity.Konfigurasi, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Konfigurasi
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Konfigurasi, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Konfigurasi); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Konfigurasi)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value
func (_m *KonfigurasiRepository) Set(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKonfigurasiRepository creates a new instance of KonfigurasiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKonfigurasiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KonfigurasiRepository {
	mock := &KonfigurasiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
