// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"

	repository "lab-ap/internal/repository"
)

// PengerjaanRepository is an autogenerated mock type for the PengerjaanRepository type
type PengerjaanRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *PengerjaanRepository) Create(p *entity.PengerjaanCourse) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PengerjaanCourse) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: mahasiswaID, aktivasiSesiID, courseID
func (_m *PengerjaanRepository) Find(mahasiswaID int, aktivasiSesiID int, courseID int) (*entity.PengerjaanCourse, error) {
	ret := _m.Called(mahasiswaID, aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *entity.PengerjaanCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (*entity.PengerjaanCourse, error)); ok {
		return rf(mahasiswaID, aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) *entity.PengerjaanCourse); ok {
		r0 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PengerjaanCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExpired provides a mock function with no fields
func (_m *PengerjaanRepository) FindExpired() ([]repository.ExpiredPengerjaan, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindExpired")
	}

	var r0 []repository.ExpiredPengerjaan
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.ExpiredPengerjaan, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.ExpiredPengerjaan); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ExpiredPengerjaan)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrCreate provides a mock function with given fields: mahasiswaID, aktivasiSesiID, courseID
func (_m *PengerjaanRepository) FindOrCreate(mahasiswaID int, aktivasiSesiID int, courseID int) (*entity.PengerjaanCourse, error) {
	ret := _m.Called(mahasiswaID, aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *entity.PengerjaanCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (*entity.PengerjaanCourse, error)); ok {
		return rf(mahasiswaID, aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) *entity.PengerjaanCourse); ok {
		r0 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PengerjaanCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(mahasiswaID, aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByAktivasiCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *PengerjaanRepository) ListByAktivasiCourse(aktivasiSesiID int, courseID int) ([]entity.PengerjaanCourse, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByAktivasiCourse")
	}

	var r0 []entity.PengerjaanCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]entity.PengerjaanCourse, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []entity.PengerjaanCourse); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PengerjaanCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByMahasiswa provides a mock function with given fields: mahasiswaID
func (_m *PengerjaanRepository) ListByMahasiswa(mahasiswaID int) ([]entity.PengerjaanCourse, error) {
	ret := _m.Called(mahasiswaID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMahasiswa")
	}

	var r0 []entity.PengerjaanCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.PengerjaanCourse, error)); ok {
		return rf(mahasiswaID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.PengerjaanCourse); ok {
		r0 = rf(mahasiswaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PengerjaanCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(mahasiswaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSelesaiForCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *PengerjaanRepository) MarkSelesaiForCourse(aktivasiSesiID int, courseID int) error {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSelesaiForCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProgressSummary provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *PengerjaanRepository) ProgressSummary(aktivasiSesiID int, courseID int) (repository.ProgressSummary, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ProgressSummary")
	}

	var r0 repository.ProgressSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (repository.ProgressSummary, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) repository.ProgressSummary); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		r0 = ret.Get(0).(repository.ProgressSummary)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: p
func (_m *PengerjaanRepository) Update(p *entity.PengerjaanCourse) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PengerjaanCourse) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPengerjaanRepository creates a new instance of PengerjaanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPengerjaanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PengerjaanRepository {
	mock := &PengerjaanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
