// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	repository "lab-ap/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// RekapRepository is an autogenerated mock type for the RekapRepository type
type RekapRepository struct {
	mock.Mock
}

// GetRekapByKelas provides a mock function with given fields: kelasID
func (_m *RekapRepository) GetRekapByKelas(kelasID int) ([]repository.RekapRow, error) {
	ret := _m.Called(kelasID)

	if len(ret) == 0 {
		panic("no return value specified for GetRekapByKelas")
	}

	var r0 []repository.RekapRow
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]repository.RekapRow, error)); ok {
		return rf(kelasID)
	}
	if rf, ok := ret.Get(0).(func(int) []repository.RekapRow); ok {
		r0 = rf(kelasID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RekapRow)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(kelasID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRekapRepository creates a new instance of RekapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRekapRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RekapRepository {
	mock := &RekapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
