// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// SesiRepository is an autogenerated mock type for the SesiRepository type
type SesiRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: s
func (_m *SesiRepository) Create(s *entity.SesiPraktikum) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.SesiPraktikum) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *SesiRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *SesiRepository) FindByID(id int) (*entity.SesiPraktikum, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.SesiPraktikum
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.SesiPraktikum, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.SesiPraktikum); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SesiPraktikum)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *SesiRepository) List() ([]entity.SesiPraktikum, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.SesiPraktikum
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.SesiPraktikum, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.SesiPraktikum); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SesiPraktikum)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: s
func (_m *SesiRepository) Update(s *entity.SesiPraktikum) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.SesiPraktikum) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSesiRepository creates a new instance of SesiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSesiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SesiRepository {
	mock := &SesiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
