// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// SoalRepository is an autogenerated mock type for the SoalRepository type
type SoalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: s
func (_m *SoalRepository) Create(s *entity.Soal) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Soal) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *SoalRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *SoalRepository) FindByID(id int) (*entity.Soal, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Soal
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Soal, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Soal); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Soal)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByCourse provides a mock function with given fields: courseID
func (_m *SoalRepository) ListByCourse(courseID int) ([]entity.Soal, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCourse")
	}

	var r0 []entity.Soal
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.Soal, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.Soal); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Soal)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PoolAll provides a mock function with given fields: courseID
func (_m *SoalRepository) PoolAll(courseID int) ([]entity.Soal, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for PoolAll")
	}

	var r0 []entity.Soal
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.Soal, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.Soal); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Soal)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PoolByDifficulty provides a mock function with given fields: courseID, diff
func (_m *SoalRepository) PoolByDifficulty(courseID int, diff entity.Difficulty) ([]entity.Soal, error) {
	ret := _m.Called(courseID, diff)

	if len(ret) == 0 {
		panic("no return value specified for PoolByDifficulty")
	}

	var r0 []entity.Soal
	var r1 error
	if rf, ok := ret.Get(0).(func(int, entity.Difficulty) ([]entity.Soal, error)); ok {
		return rf(courseID, diff)
	}
	if rf, ok := ret.Get(0).(func(int, entity.Difficulty) []entity.Soal); ok {
		r0 = rf(courseID, diff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Soal)
		}
	}

	if rf, ok := ret.Get(1).(func(int, entity.Difficulty) error); ok {
		r1 = rf(courseID, diff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PoolByKategori provides a mock function with given fields: courseID, kat
func (_m *SoalRepository) PoolByKategori(courseID int, kat entity.KategoriUjian) ([]entity.Soal, error) {
	ret := _m.Called(courseID, kat)

	if len(ret) == 0 {
		panic("no return value specified for PoolByKategori")
	}

	var r0 []entity.Soal
	var r1 error
	if rf, ok := ret.Get(0).(func(int, entity.KategoriUjian) ([]entity.Soal, error)); ok {
		return rf(courseID, kat)
	}
	if rf, ok := ret.Get(0).(func(int, entity.KategoriUjian) []entity.Soal); ok {
		r0 = rf(courseID, kat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Soal)
		}
	}

	if rf, ok := ret.Get(1).(func(int, entity.KategoriUjian) error); ok {
		r1 = rf(courseID, kat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: s
func (_m *SoalRepository) Update(s *entity.Soal) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Soal) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSoalRepository creates a new instance of SoalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSoalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SoalRepository {
	mock := &SoalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
