// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// SoalTerpilihRepository is an autogenerated mock type for the SoalTerpilihRepository type
type SoalTerpilihRepository struct {
	mock.Mock
}

// BulkCreate provides a mock function with given fields: items
func (_m *SoalTerpilihRepository) BulkCreate(items []entity.SoalTerpilih) error {
	ret := _m.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]entity.SoalTerpilih) error); ok {
		r0 = rf(items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsForAktivasiCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *SoalTerpilihRepository) ExistsForAktivasiCourse(aktivasiSesiID int, courseID int) (bool, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsForAktivasiCourse")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (bool, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *SoalTerpilihRepository) FindByID(id int) (*entity.SoalTerpilih, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.SoalTerpilih
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.SoalTerpilih, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.SoalTerpilih); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SoalTerpilih)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByAktivasiCourse provides a mock function with given fields: aktivasiSesiID, courseID
func (_m *SoalTerpilihRepository) ListByAktivasiCourse(aktivasiSesiID int, courseID int) ([]entity.SoalTerpilih, error) {
	ret := _m.Called(aktivasiSesiID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByAktivasiCourse")
	}

	var r0 []entity.SoalTerpilih
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]entity.SoalTerpilih, error)); ok {
		return rf(aktivasiSesiID, courseID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []entity.SoalTerpilih); ok {
		r0 = rf(aktivasiSesiID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SoalTerpilih)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(aktivasiSesiID, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSoalTerpilihRepository creates a new instance of SoalTerpilihRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSoalTerpilihRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SoalTerpilihRepository {
	mock := &SoalTerpilihRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
