// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	entity "lab-ap/internal/entity"

	mock "github.com/stretchr/testify/mock"

	repository "lab-ap/internal/repository"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// BulkUpsert provides a mock function with given fields: users
func (_m *UserRepository) BulkUpsert(users []entity.User) error {
	ret := _m.Called(users)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]entity.User) error); ok {
		r0 = rf(users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimRoster provides a mock function with given fields: userID, supabaseUID, email
func (_m *UserRepository) ClaimRoster(userID int, supabaseUID string, email *string) error {
	ret := _m.Called(userID, supabaseUID, email)

	if len(ret) == 0 {
		panic("no return value specified for ClaimRoster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, *string) error); ok {
		r0 = rf(userID, supabaseUID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountByRole provides a mock function with given fields: role
func (_m *UserRepository) CountByRole(role entity.RoleType) (int64, error) {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for CountByRole")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.RoleType) (int64, error)); ok {
		return rf(role)
	}
	if rf, ok := ret.Get(0).(func(entity.RoleType) int64); ok {
		r0 = rf(role)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(entity.RoleType) error); ok {
		r1 = rf(role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountPerKelasShift provides a mock function with no fields
func (_m *UserRepository) CountPerKelasShift() ([]repository.KelasShiftCount, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountPerKelasShift")
	}

	var r0 []repository.KelasShiftCount
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]repository.KelasShiftCount, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []repository.KelasShiftCount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.KelasShiftCount)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountRegistered provides a mock function with given fields: registered
func (_m *UserRepository) CountRegistered(registered bool) (int64, error) {
	ret := _m.Called(registered)

	if len(ret) == 0 {
		panic("no return value specified for CountRegistered")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (int64, error)); ok {
		return rf(registered)
	}
	if rf, ok := ret.Get(0).(func(bool) int64); ok {
		r0 = rf(registered)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(registered)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: u
func (_m *UserRepository) Create(u *entity.User) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *UserRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: email
func (_m *UserRepository) FindByEmail(email string) (*entity.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *UserRepository) FindByID(id int) (*entity.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNIM provides a mock function with given fields: nim
func (_m *UserRepository) FindByNIM(nim string) (*entity.User, error) {
	ret := _m.Called(nim)

	if len(ret) == 0 {
		panic("no return value specified for FindByNIM")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(nim)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(nim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nim)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySupabaseUserID provides a mock function with given fields: uid
func (_m *UserRepository) FindBySupabaseUserID(uid string) (*entity.User, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupabaseUserID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: role, kelasID, shift
func (_m *UserRepository) List(role string, kelasID *int, shift *int) ([]entity.User, error) {
	ret := _m.Called(role, kelasID, shift)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *int, *int) ([]entity.User, error)); ok {
		return rf(role, kelasID, shift)
	}
	if rf, ok := ret.Get(0).(func(string, *int, *int) []entity.User); ok {
		r0 = rf(role, kelasID, shift)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *int, *int) error); ok {
		r1 = rf(role, kelasID, shift)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAsisten provides a mock function with no fields
func (_m *UserRepository) ListAsisten() ([]entity.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAsisten")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: u
func (_m *UserRepository) Update(u *entity.User) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePasswordByEmail provides a mock function with given fields: email, hash
func (_m *UserRepository) UpdatePasswordByEmail(email string, hash string) (int64, error) {
	ret := _m.Called(email, hash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordByEmail")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return rf(email, hash)
	}
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(email, hash)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
